# Generated by Django 3.2.25 on 2025-02-04 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_user_message_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulance_request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('request', models.CharField(max_length=100)),
                ('AMBULANCE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.ambulance_table')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user_table')),
            ],
        ),
    ]
