# Generated by Django 3.2.25 on 2025-02-07 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_ambulance_request_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_table',
            name='PlaceDetails',
        ),
    ]
