# Generated by Django 3.2.25 on 2025-02-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_alter_location_table_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_table',
            name='Longitude',
            field=models.CharField(max_length=100),
        ),
    ]
