# Generated by Django 3.2.25 on 2025-02-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_auto_20250216_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance_request_table',
            name='AMBULANCE_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.ambulance_table'),
        ),
    ]
