# Generated by Django 3.2.25 on 2025-03-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_alter_ambulance_request_table_ambulance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance_request_table',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
