# Generated by Django 3.2.25 on 2025-03-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_ambulance_request_table_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='place',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='post',
        ),
    ]
