# Generated by Django 3.2.25 on 2025-03-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_auto_20250316_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance_request_table',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
