# Generated by Django 3.2.25 on 2025-03-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_ambulance_request_table_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_table',
            name='PatientCondition',
        ),
        migrations.AddField(
            model_name='patient_table',
            name='voice_message',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/'),
        ),
    ]
