# Generated by Django 3.2.25 on 2025-03-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_auto_20250316_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_table',
            old_name='voice_message',
            new_name='PatientCondition',
        ),
    ]
