# Generated by Django 3.2.25 on 2025-03-23 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_chatmessage_chatsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
